coverage:
  status:
    project:
      default:
        target: 83.33%
    patch:
      default:
        target: 75%

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: proj-
        type: project
        target: 75%
        threshold: 1%
      - name_prefix: patch-
        type: patch
        target: 75%
  individual_flags:
    - name: unitttest
      paths:
        - src/
      carryforward: true
      statuses:
        - name_prefix: proj-
          type: project
          target: 87.5%

ignore:
  - tests/*