name: "Documentation auto generation"

on:
  push:
    branches: [ master ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up the Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
      run: pip install -r requirements.txt
    - name: Build docs with pdoc
      run: pdoc --html src --force --output-dir docs

    - name: Commit documentation changes
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'karafra'
          git config --global user.email '55988328@users.noreply.github.com'
          git add -A
          git commit -m "Automated documentation update. :books:"
          git push
        fi

